name: Send Discord Scrum Message

on:
  schedule:
    - cron: '45 12 * * *'  

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        run: |
          tomorrow=$(date -d "+1 day" +'%m월 %d일')  # 날짜 +1일
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"'"$tomorrow 스크럼 회의록"'"}' \
               ${{ secrets.DISCORD_WEBHOOK }}
